import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {all,one,run,stmt,db,uid,config,seedDemo,getStore} from '@/lib/db';
import {AppError,ensureSession,sessionFor,viewer,checkMutation,requireAdmin,limit,hashPassword,verifyPassword,hash,token,cookie,sendPendingEmails} from '@/lib/auth';
import {email,password,addressSchema} from '@/lib/validation';
import {getCart,changeCart,startCheckout,getOrder,webhook,paymentStatus,reconcileExpired} from '@/lib/commerce';
import {adminData,adminAction} from '@/lib/admin';
export const dynamic='force-dynamic';
function json(data:any,status=200,setCookie?:string|null){const h:Record<string,string>={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};if(setCookie)h['Set-Cookie']=setCookie;return Response.json(data,{status,headers:h})}
async function handle(req:Request,ctx:{params:Promise<{path:string[]}>}){
 try{
 const {path}=await ctx.params,action=path.join('/');
 if(action==='maintenance'&&req.method==='POST'){const secret=config('MAINTENANCE_SECRET');const provided=req.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(secret.length<32||hash(provided)!==hash(secret))throw new AppError('Unauthorized.',401);const recovered=await reconcileExpired();await sendPendingEmails();return json(recovered)}
 if(action==='stripe/webhook'&&req.method==='POST'){await webhook(req);return json({received:true})}
 await seedDemo();
 if(path[0]==='media'&&req.method==='GET'){if(!env.BUCKET)throw new AppError('Image storage is unavailable.',503);const file=await env.BUCKET.get(path.slice(1).join('/'));if(!file)throw new AppError('Image not found.',404);return new Response(file.body as any,{headers:{'Content-Type':file.httpMetadata?.contentType??'application/octet-stream','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
 if(req.method==='GET'){
 if(action==='session'){const {session,setCookie}=await ensureSession(req);return json({user:viewer(session),csrf:session.csrf,cart:await getCart(session.id)},200,setCookie)}
 if(action==='catalog')return json(await getStore());
 if(action==='admin'){await requireAdmin(req);return json(await adminData())}
 const s=await sessionFor(req);if(!s)throw new AppError('Sign in to continue.',401);
 if(action==='account'){if(!s.user_id)throw new AppError('Sign in to view your account.',401);return json({user:viewer(s),orders:await all('SELECT id,total,currency,status,demo,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC',s.user_id),addresses:(await all('SELECT id,data FROM addresses WHERE user_id=?',s.user_id)).map(a=>({id:a.id,...JSON.parse(a.data)}))})}
 if(path[0]==='order')return json(await getOrder(path.slice(1).join('/'),s));
 if(action==='payment-status')return json(await paymentStatus(new URL(req.url).searchParams.get('session_id')??'',s));
 if(path[0]==='customer'){await requireAdmin(req);return json({customer:await one("SELECT id,name,email,created_at FROM users WHERE id=? AND role='customer'",path[1]),orders:await all('SELECT id,total,currency,status,demo,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC',path[1])})}
 throw new AppError('Page not found.',404)
 }
 const s=await checkMutation(req);
 if(action==='admin/upload'){await requireAdmin(req);if(!env.BUCKET)throw new AppError('Image storage is not connected.',503);if(Number(req.headers.get('content-length')||0)>16000000)throw new AppError('Upload at most 15 MB at a time.');const reader=req.body?.getReader();if(!reader)throw new AppError('Choose an image.');let length=0;const chunks:Uint8Array[]=[];while(true){const part=await reader.read();if(part.done)break;length+=part.value.length;if(length>16000000){await reader.cancel();throw new AppError('Upload at most 15 MB at a time.',413)}chunks.push(part.value)}const payload=new Uint8Array(length);let offset=0;for(const chunk of chunks){payload.set(chunk,offset);offset+=chunk.length}const limited=new Request(req.url,{method:'POST',headers:{'Content-Type':req.headers.get('content-type')||''},body:payload});const form=await limited.formData();const files=form.getAll('files');if(!files.length||files.length>8)throw new AppError('Choose between 1 and 8 images.');const result=[];for(const f of files){if(!(f instanceof File)||f.size>5*1024*1024)throw new AppError('Each image must be smaller than 5 MB.');const bytes=new Uint8Array(await f.arrayBuffer());const type=bytes.length>128&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255&&bytes[bytes.length-2]===255&&bytes[bytes.length-1]===217?'image/jpeg':bytes.length>32&&[137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n)&&String.fromCharCode(...bytes.slice(12,16))==='IHDR'?'image/png':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP'?'image/webp':null;if(!type)throw new AppError('Use a valid JPEG, PNG or WebP image.');const key=uid()+'.'+type.split('/')[1];await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});result.push({url:'/api/media/'+key,alt:f.name.replace(/\.[^.]+$/,'')})}return json({images:result})}
 if(!req.headers.get('content-type')?.includes('application/json'))throw new AppError('JSON input is required.',415);if(Number(req.headers.get('content-length')||0)>100000)throw new AppError('Request is too large.',413);const b=await req.json() as any;
 if(path[0]==='auth'){
 const ip=req.headers.get('cf-connecting-ip')??'local';await limit('auth-ip:'+hash(ip),40,900000);
 if(action==='auth/logout'){await run('DELETE FROM sessions WHERE id=?',s.id);return json({ok:true},200,cookie('',req,0))}
 if(action==='auth/register'||action==='auth/login'||action==='auth/setup'){
 const e=email.parse(b.email),pw=password.parse(b.password);await limit('auth-account:'+hash(e),10,900000);let u=await one('SELECT * FROM users WHERE email=?',e);
 if(action==='auth/login'){const dummy='scrypt:32768:8:3:00000000000000000000000000000000:'+('00'.repeat(32));if(!verifyPassword(pw,u?.password_hash??dummy)||!u)throw new AppError('The email or password is incorrect.',401)}
 else{
 if(action==='auth/setup'){const setup=config('ADMIN_SETUP_TOKEN');if(!setup||typeof b.setupToken!=='string'||hash(b.setupToken)!==hash(setup))throw new AppError('A valid owner setup token is required.',403);if(await one('SELECT user_id FROM admins LIMIT 1'))throw new AppError('An administrator already exists. Sign in instead.',409)}
 if(u)throw new AppError('Unable to create this account. Try signing in or resetting your password.');
 const name=z.string().trim().min(2).max(120).parse(b.name),id=uid(),role=action==='auth/setup'?'admin':'customer';const writes=[stmt('INSERT INTO users (id,email,name,password_hash,role) VALUES (?,?,?,?,?)',id,e,name,hashPassword(pw),role),stmt(role==='admin'?'INSERT INTO admins (user_id) VALUES (?)':'INSERT INTO customers (user_id) VALUES (?)',id)];await db().batch(writes);u={id,name,email:e,role};
 }
 const raw=token(),csrf=token();if(s.user_id&&s.user_id!==u.id){const freshId=uid();await db().batch([stmt('DELETE FROM sessions WHERE id=?',s.id),stmt('INSERT INTO sessions (id,user_id,token_hash,csrf,expires) VALUES (?,?,?,?,?)',freshId,u.id,hash(raw),csrf,Date.now()+604800000),stmt('INSERT INTO carts (id,session_id) VALUES (?,?)',uid(),freshId)])}else{await run('UPDATE sessions SET user_id=?,token_hash=?,csrf=?,expires=? WHERE id=?',u.id,hash(raw),csrf,Date.now()+604800000,s.id);}return json({user:{id:u.id,name:u.name,email:u.email,role:u.role},csrf},200,cookie(raw,req));
 }
 if(action==='auth/forgot'){const e=email.parse(b.email);await limit('reset:'+hash(e),3,3600000);const u=await one('SELECT id FROM users WHERE email=?',e);if(u){const raw=token(),link=(config('APP_URL')||'http://localhost:5173')+'/account/reset?token='+raw;await db().batch([stmt('INSERT INTO reset_tokens (hash,user_id,expires) VALUES (?,?,?)',hash(raw),u.id,Date.now()+1800000),stmt('INSERT INTO email_outbox (id,dedupe_key,recipient,subject,body) VALUES (?,?,?,?,?)',uid(),'reset:'+hash(raw),e,'Reset your Dress to Impress password','Use this link within 30 minutes to reset your password: '+link)]);await sendPendingEmails()}return json({message:'If an account matches, a reset link will be sent. Delivery requires the store’s email service to be configured.'})}
 if(action==='auth/reset'){const raw=z.string().min(32).max(200).parse(b.token),pw=password.parse(b.password),h=hash(raw),r=await one('SELECT * FROM reset_tokens WHERE hash=? AND used=0 AND expires>?',h,Date.now());if(!r)throw new AppError('This reset link is invalid or expired. Request a new one.');await db().batch([stmt('UPDATE users SET password_hash=? WHERE id=? AND EXISTS(SELECT 1 FROM reset_tokens WHERE hash=? AND used=0 AND expires>?)',hashPassword(pw),r.user_id,h,Date.now()),stmt('DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM reset_tokens WHERE hash=? AND used=0)',r.user_id,h),stmt('UPDATE reset_tokens SET used=used+1 WHERE hash=?',h)]);return json({message:'Password updated. You can now sign in.'},200,cookie('',req,0))}
 }
 if(action==='cart/replace'){const input=z.object({oldVariantId:z.string(),newVariantId:z.string(),quantity:z.number().int().min(1).max(20)}).parse(b);const cart=await one('SELECT id FROM carts WHERE session_id=?',s.id);const old=await one('SELECT ci.*,v.product_id FROM cart_items ci JOIN product_variants v ON v.id=ci.variant_id WHERE ci.cart_id=? AND ci.variant_id=?',cart.id,input.oldVariantId);const next=await one('SELECT v.product_id,i.stock,p.published FROM product_variants v JOIN inventory i ON i.variant_id=v.id JOIN products p ON p.id=v.product_id WHERE v.id=?',input.newVariantId);if(!old||!next||old.product_id!==next.product_id||!next.published||next.stock<input.quantity)throw new AppError('That variant is unavailable.');await db().batch([stmt('DELETE FROM cart_items WHERE cart_id=? AND variant_id=?',cart.id,input.oldVariantId),stmt('INSERT INTO cart_items (id,cart_id,variant_id,quantity) VALUES (?,?,?,?) ON CONFLICT(cart_id,variant_id) DO UPDATE SET quantity=excluded.quantity',uid(),cart.id,input.newVariantId,input.quantity)]);return json({cart:await getCart(s.id)})}
 if(action==='cart'){const q=z.object({variantId:z.string(),quantity:z.number().int().min(0).max(20),add:z.boolean().optional()}).parse(b);return json({cart:await changeCart(s.id,q.variantId,q.quantity,q.add)})}
 if(action==='checkout')return json(await startCheckout(s,b));
 if(action==='newsletter'){const e=email.parse(b.email);if(b.consent!==true)throw new AppError('Please agree to receive email updates.');await limit('newsletter:'+s.id,5,3600000);await run('INSERT OR IGNORE INTO newsletter_subscribers (id,email) VALUES (?,?)',uid(),e);return json({message:'You’re on the list. Look out for the next edit.'})}
 if(action==='account/profile'){if(!s.user_id)throw new AppError('Please sign in.',401);const name=z.string().trim().min(2).max(120).parse(b.name);await run('UPDATE users SET name=? WHERE id=?',name,s.user_id);return json({ok:true})}
 if(action==='account/address'){if(!s.user_id)throw new AppError('Please sign in.',401);const a=addressSchema.parse(b);if(b.id){const result=await run('UPDATE addresses SET data=? WHERE id=? AND user_id=?',JSON.stringify(a),String(b.id),s.user_id);if(!result.meta.changes)throw new AppError('Address not found.',404)}else{if((await all('SELECT id FROM addresses WHERE user_id=?',s.user_id)).length>=10)throw new AppError('You can save up to 10 addresses.');await run('INSERT INTO addresses (id,user_id,data) VALUES (?,?,?)',uid(),s.user_id,JSON.stringify(a))}return json({ok:true})}
 if(action==='account/address/delete'){if(!s.user_id)throw new AppError('Please sign in.',401);await run('DELETE FROM addresses WHERE id=? AND user_id=?',String(b.id),s.user_id);return json({ok:true})}
 if(path[0]==='admin'){await requireAdmin(req);if(action==='admin/reconcile')return json(await reconcileExpired());if(action==='admin/email/retry'){await sendPendingEmails();return json({ok:true})}return json(await adminAction(path.slice(1).join('/'),b))}
 throw new AppError('Action not found.',404);
 }catch(error){if(error instanceof z.ZodError)return json({error:error.issues[0]?.message??'Please check your input.'},400);if(error instanceof AppError)return json({error:error.message},error.status);const message=error instanceof Error?error.message:'';console.error('Store request failed',message.slice(0,300));if(/UNIQUE constraint/i.test(message))return json({error:'That email, slug or SKU is already in use. Choose another value.'},409);if(/CHECK constraint.*stock|Stock or price changed/i.test(message))return json({error:'Stock changed since this page loaded. Refresh before updating inventory.'},409);if(/FOREIGN KEY constraint/i.test(message))return json({error:'This item has order history. Unpublish it or set its stock to zero instead of deleting it.'},409);return json({error:'We couldn’t complete that request. Your input is saved; please try again.'},500)}
}
export const GET=handle;export const POST=handle;

