import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as crypto from 'node:crypto';
import * as zod from 'zod';
const sql=new DatabaseSync(':memory:');
for(const file of ['0000_futuristic_silk_fever.sql','0001_silky_mastermind.sql','0003_friendly_korvac.sql'])sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
sql.exec(`INSERT INTO users(id,email,name,password_hash) VALUES('u','test@example.invalid','Test','fixture');
INSERT INTO sessions(id,user_id,token_hash,csrf,expires) VALUES('s','u','hash','csrf',9999999999999);
INSERT INTO carts(id,session_id) VALUES('c','s');
INSERT INTO categories(id,name,slug) VALUES('cat','Test','test');
INSERT INTO products(id,name,slug,description,price,sku,category_id,materials,care,published) VALUES('p','Test','test','Test product',98125,'TEST','cat','','',1);
INSERT INTO product_variants(id,product_id,size,color) VALUES('v','p','S','Black');
INSERT INTO inventory(variant_id,stock) VALUES('v',3);
INSERT INTO cart_items(id,cart_id,variant_id,quantity) VALUES('ci','c','v',2);`);
const settings={currency:'TND',paymentMethod:'cod',liveSales:true,shippingCountries:'TN',shippingCities:'Sousse',shippingFee:0,taxRate:0};
class AppError extends Error{constructor(message,status=400){super(message);this.status=status}}
const database={one:async(q,...p)=>sql.prepare(q).get(...p),all:async(q,...p)=>sql.prepare(q).all(...p),run:async(q,...p)=>{const r=sql.prepare(q).run(...p);return {meta:{changes:r.changes}}},stmt:(query,...args)=>({query,args}),uid:()=>crypto.randomUUID(),config:()=>'',getStore:async()=>({settings}),db:()=>({batch:async statements=>{sql.exec('BEGIN');try{for(const s of statements)sql.prepare(s.query).run(...s.args);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}})};
const modules=new Map();
function load(name){if(modules.has(name))return modules.get(name).exports;const module={exports:{}};modules.set(name,module);const code=ts.transpileModule(readFileSync(new URL('../lib/'+name+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const factory=vm.runInNewContext('(function(require,module,exports){'+code+'\n})',{Buffer,URLSearchParams,Date,console,fetch:()=>{throw Error('COD must not call a payment provider');}});factory(dep=>{if(dep==='server-only')return {};if(dep==='node:crypto')return crypto;if(dep==='zod')return zod;if(dep==='./db')return database;if(dep==='./auth')return {AppError,sendPendingEmails:async()=>{}};if(dep.startsWith('./'))return load(dep.slice(2));throw Error(dep);},module,module.exports);return module.exports;}
const commerce=load('commerce'),admin=load('admin'),cod=load('cod');
const customer={id:'s',user_id:'u'};
const address={name:'Test Customer',email:'test@example.invalid',phone:'20123456',line1:'123 Test Road',city:'Sousse',postalCode:'4000',country:'TN'};
const input={address,requestKey:'cod-test-request-0001'};
await assert.rejects(commerce.startCheckout({id:'s'},input),e=>e.status===401);
await assert.rejects(commerce.startCheckout(customer,{...input,address:{...address,city:'Tunis'}}),/Sousse/);
await assert.rejects(commerce.startCheckout(customer,{...input,address:{...address,phone:''}}),/phone/);
settings.shippingCities='';
await assert.rejects(commerce.startCheckout(customer,{...input,address:{...address,country:'FR',city:'Paris'}}));
input.address={...address,city:'Tunis'};
const first=await commerce.startCheckout(customer,input);
const id=first.url.split('/').pop();let order=sql.prepare('SELECT * FROM orders WHERE id=?').get(id);
assert.equal(order.status,'pending');assert.equal(order.payment_status,'cod_pending');assert.equal(order.payment_method,'cod');assert.equal(order.total,196250);
assert.equal(sql.prepare('SELECT stock FROM inventory').get().stock,1);
assert.equal(sql.prepare('SELECT count(*) n FROM cart_items').get().n,0);
assert.equal((await commerce.startCheckout(customer,input)).url,first.url);
assert.equal(sql.prepare('SELECT count(*) n FROM orders').get().n,1);
await assert.rejects(cod.collectCod(id),/shipped or delivered/);
await admin.adminAction('orders/status',{id,status:'cancelled'});
assert.equal(sql.prepare('SELECT stock FROM inventory').get().stock,3);
await assert.rejects(admin.adminAction('orders/status',{id,status:'cancelled'}));
assert.equal(sql.prepare('SELECT stock FROM inventory').get().stock,3);
assert.equal((await commerce.startCheckout(customer,input)).url,first.url);
sql.exec("INSERT INTO cart_items(id,cart_id,variant_id,quantity) VALUES('ci2','c','v',1)");
const next=await commerce.startCheckout(customer,{...input,requestKey:'cod-test-request-0002'}),nextId=next.url.split('/').pop();
await admin.adminAction('orders/status',{id:nextId,status:'processing'});
await admin.adminAction('orders/status',{id:nextId,status:'shipped'});
await cod.collectCod(nextId);await cod.collectCod(nextId);
await admin.adminAction('orders/status',{id:nextId,status:'delivered'});
assert.equal(sql.prepare('SELECT payment_status FROM orders WHERE id=?').get(nextId).payment_status,'paid');
await assert.rejects(admin.adminAction('orders/status',{id:nextId,status:'cancelled'}));
await commerce.reconcileExpired();assert.equal(sql.prepare('SELECT stock FROM inventory').get().stock,2);
settings.liveSales=false;
sql.exec("INSERT INTO cart_items(id,cart_id,variant_id,quantity) VALUES('ci3','c','v',1)");
const demo=await commerce.startCheckout(customer,{...input,requestKey:'cod-test-request-0003',confirmDemo:true});
const demoOrder=sql.prepare('SELECT * FROM orders WHERE id=?').get(demo.url.split('/').pop());
assert.equal(demoOrder.demo,1);assert.equal(demoOrder.payment_status,'demo_cod_pending');
assert.deepEqual(sql.prepare('PRAGMA foreign_key_check').all(),[]);
console.log('PASS COD: TND totals, account/city/phone checks, unpaid orders, idempotency, stock reservation/cart clearing, one-time cancellation restock, collection, delivery and demo labeling; no Stripe requests.');
