import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes} from 'node:crypto';
const origin='http://localhost:5173';
const results=[];const suffix=randomUUID().slice(0,8);
const password='Qa-only-'+randomBytes(16).toString('hex');
const adminEmail='qa-owner-'+suffix+'@example.test';
const customerEmail='qa-customer-'+suffix+'@example.test';
const setupToken=readFileSync('.dev.vars','utf8').match(/^ADMIN_SETUP_TOKEN=(.+)$/m)?.[1];
const tracked={users:[],products:[],categories:[],orders:[],sessions:[]};
class Client{cookie='';csrf='';async call(path,body,headers={}){const response=await fetch(origin+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:this.cookie,...(body!==undefined?{Origin:origin,'x-csrf-token':this.csrf,...(body instanceof FormData?{}:{'Content-Type':'application/json'})}:{}),...headers},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const c=response.headers.get('set-cookie');if(c)this.cookie=c.split(';')[0];const responseText=await response.text();let data;try{data=JSON.parse(responseText)}catch{data={error:responseText}}if(data.csrf)this.csrf=data.csrf;return {status:response.status,data}}async init(){return this.call('session')}}
async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS '+name)}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL '+name+': '+e.message)}}
const owner=new Client(),guest=new Client(),customer=new Client(),other=new Client();await Promise.all([owner.init(),guest.init(),customer.init(),other.init()]);
await test('Unauthorized admin API and cross-origin write rejected',async()=>{assert.equal((await guest.call('admin')).status,403);assert.equal((await guest.call('newsletter',{email:'qa@example.test',consent:true},{Origin:'https://attacker.example'})).status,403);assert.equal((await guest.call('cart',{variantId:'demo-1-S',quantity:1},{'x-csrf-token':'invalid'})).status,403)});
await test('Create first admin using setup token; no default password',async()=>{const r=await owner.call('auth/setup',{email:adminEmail,password,name:'QA Owner',setupToken});assert.equal(r.status,200,JSON.stringify(r.data));tracked.users.push(r.data.user.id);assert.equal(r.data.user.role,'admin')});
await test('Customer registration cannot select admin role',async()=>{const r=await customer.call('auth/register',{email:customerEmail,password,name:'QA Customer',role:'admin'});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.user.role,'customer');tracked.users.push(r.data.user.id);assert.equal((await customer.call('admin')).status,403)});
let category,product,original;
await test('Create/edit category and database-backed storefront',async()=>{const r=await owner.call('admin/categories/save',{name:'QA Edit '+suffix,slug:'qa-edit-'+suffix,description:'QA disposable category',image:'',position:99});assert.equal(r.status,200,JSON.stringify(r.data));category=r.data.id;tracked.categories.push(category);assert.ok((await guest.call('catalog')).data.categories.some(c=>c.id===category))});
await test('Create product with images, variants, price and stock',async()=>{const catalog=(await guest.call('catalog')).data;original=catalog;const r=await owner.call('admin/products/save',{name:'QA Test Piece '+suffix,slug:'qa-piece-'+suffix,description:'Disposable product for local integration testing only.',price:9950,salePrice:8500,sku:'QA-'+suffix,categoryId:category,materials:'Demo fabric',care:'Demo care',featured:false,isNew:false,bestSeller:false,published:true,demo:true,images:[{url:catalog.products[0].images[0].url,alt:'QA demo product'}],variants:[{size:'M',color:'Black',stock:2,threshold:1},{size:'L',color:'Black',stock:0,threshold:1}]});assert.equal(r.status,200,JSON.stringify(r.data));product=(await guest.call('catalog')).data.products.find(p=>p.id===r.data.id);tracked.products.push(product.id);assert.equal(product.salePrice,8500)});
await test('Server rejects invalid sale price and duplicate SKU',async()=>{const p={...product,featured:false,isNew:false,bestSeller:false,published:true,demo:true,salePrice:10000};assert.equal((await owner.call('admin/products/save',p)).status,400)});
await test('Out-of-stock and unavailable quantity cannot enter cart',async()=>{const out=product.variants.find(v=>v.size==='L'),v=product.variants.find(v=>v.size==='M');assert.equal((await customer.call('cart',{variantId:out.id,quantity:1,add:true})).status,400);assert.equal((await customer.call('cart',{variantId:v.id,quantity:3,add:true})).status,400);assert.equal((await customer.call('cart',{variantId:v.id,quantity:1,add:true})).status,200);assert.equal((await guest.call('cart',{variantId:v.id,quantity:2,add:true})).status,200)});
const address={name:'QA Test Customer',email:customerEmail,phone:'',line1:'1 Test Address',line2:'',city:'Test City',postalCode:'00000',country:'US'};
await test('Rejected demo acknowledgement does not reserve stock',async()=>{const r=await customer.call('checkout',{address,requestKey:randomUUID(),confirmDemo:false});assert.equal(r.status,400);assert.equal((await guest.call('catalog')).data.products.find(p=>p.id===product.id).variants.find(v=>v.size==='M').stock,2)});
let orderId,requestKey=randomUUID();
await test('Checkout uses server price and confirms a demo order',async()=>{const r=await customer.call('checkout',{address,requestKey,confirmDemo:true,total:1,price:1});assert.equal(r.status,200,JSON.stringify(r.data));orderId=r.data.url.split('/').pop();tracked.orders.push(orderId);const o=await customer.call('order/'+orderId);assert.equal(o.status,200);assert.equal(o.data.total,8500);assert.equal(o.data.demo,1);assert.equal((await customer.call('session')).data.cart.length,0)});
await test('Order retry is idempotent and preserves newly added cart item',async()=>{const v=product.variants.find(v=>v.size==='M');await customer.call('cart',{variantId:v.id,quantity:1,add:true});const r=await customer.call('checkout',{address,requestKey,confirmDemo:true});assert.equal(r.data.url,'/order/'+orderId);assert.equal((await customer.call('session')).data.cart.length,1);await customer.call('cart',{variantId:v.id,quantity:0})});
await test('Stale cart fails atomically after stock changes',async()=>{const r=await guest.call('checkout',{address:{...address,email:'qa-guest@example.test'},requestKey:randomUUID(),confirmDemo:true});assert.equal(r.status,400);assert.equal((await guest.call('catalog')).data.products.find(p=>p.id===product.id).variants.find(v=>v.size==='M').stock,1)});
await test('Metadata edit cannot restore purchased stock; stale explicit stock rejected',async()=>{const stale={...product,description:'QA revised description with original stock snapshot.',featured:false,isNew:false,bestSeller:false,published:true,demo:true,variants:product.variants.map(v=>({...v,expectedStock:v.stock}))};assert.equal((await owner.call('admin/products/save',stale)).status,200);const v=(await guest.call('catalog')).data.products.find(p=>p.id===product.id).variants.find(v=>v.size==='M');assert.equal(v.stock,1);assert.equal((await owner.call('admin/inventory',{id:v.id,expectedStock:2,stock:8,threshold:1})).status,409);assert.equal((await owner.call('admin/inventory',{id:v.id,expectedStock:1,stock:4,threshold:2})).status,200)});
await test('Two checkouts racing for the last item cannot oversell',async()=>{const v=(await guest.call('catalog')).data.products.find(p=>p.id===product.id).variants.find(v=>v.size==='M');assert.equal((await owner.call('admin/inventory',{id:v.id,expectedStock:v.stock,stock:1,threshold:1})).status,200);const a=new Client(),b=new Client();await Promise.all([a.init(),b.init()]);await Promise.all([a.call('cart',{variantId:v.id,quantity:1,add:true}),b.call('cart',{variantId:v.id,quantity:1,add:true})]);const race=await Promise.all([a.call('checkout',{address:{...address,email:'qa-race-a@example.test'},requestKey:randomUUID(),confirmDemo:true}),b.call('checkout',{address:{...address,email:'qa-race-b@example.test'},requestKey:randomUUID(),confirmDemo:true})]);assert.equal(race.filter(r=>r.status===200).length,1);assert.ok(race.some(r=>[400,409].includes(r.status)));tracked.orders.push(race.find(r=>r.status===200).data.url.split('/').pop());assert.equal((await guest.call('catalog')).data.products.find(p=>p.id===product.id).variants.find(v=>v.id===v.id).stock>=0,true);assert.equal((await owner.call('admin/inventory',{id:v.id,expectedStock:0,stock:4,threshold:2})).status,200)});
await test('Customers cannot read another customer order or address',async()=>{assert.equal((await other.call('order/'+orderId)).status,404);const a=await customer.call('account/address',address);assert.equal(a.status,200);const own=(await customer.call('account')).data;assert.equal(own.orders.length,1);assert.equal(own.addresses.length,1);assert.equal((await other.call('account/address',{...address,id:own.addresses[0].id})).status,401)});
await test('Switching accounts revokes previous order access',async()=>{const e='qa-second-'+suffix+'@example.test';const r=await customer.call('auth/register',{email:e,password,name:'QA Second'});assert.equal(r.status,200,JSON.stringify(r.data));tracked.users.push(r.data.user.id);assert.equal((await customer.call('order/'+orderId)).status,404);const login=await customer.call('auth/login',{email:customerEmail,password});assert.equal(login.status,200);assert.equal((await customer.call('order/'+orderId)).status,200)});
await test('Admin order status changes and customer management',async()=>{assert.equal((await owner.call('admin/orders/status',{id:orderId,status:'processing'})).status,200);assert.equal((await owner.call('admin/orders/status',{id:orderId,status:'delivered'})).status,400);assert.equal((await owner.call('admin/orders/status',{id:orderId,status:'shipped'})).status,200);assert.equal((await owner.call('admin/orders/status',{id:orderId,status:'delivered'})).status,200);const a=(await owner.call('admin')).data;assert.ok(a.customers.some(c=>c.email===customerEmail));assert.equal(a.orders.find(o=>o.id===orderId).status,'delivered')});
await test('Homepage and settings edits persist and restore',async()=>{assert.equal((await owner.call('admin/homepage',{...original.home,heading:'QA verified homepage'})).status,200);assert.equal((await guest.call('catalog')).data.home.heading,'QA verified homepage');await owner.call('admin/homepage',original.home);assert.equal((await owner.call('admin/settings',{...original.settings,promo:'ignored',phone:'QA placeholder'})).status,200);assert.equal((await guest.call('catalog')).data.settings.phone,'QA placeholder');await owner.call('admin/settings',original.settings);assert.equal((await owner.call('admin/settings',{...original.settings,liveSales:true})).status,400)});
await test('Product duplicate/delete and publish/unpublish',async()=>{const r=await owner.call('admin/products/duplicate',{id:product.id});assert.equal(r.status,200,JSON.stringify(r.data));tracked.products.push(r.data.id);assert.ok(!(await guest.call('catalog')).data.products.some(p=>p.id===r.data.id));assert.equal((await owner.call('admin/products/delete',{id:r.data.id})).status,200);assert.equal((await owner.call('admin/products/delete',{id:product.id})).status,409);assert.equal((await owner.call('admin/products/publish',{id:product.id,published:false})).status,200);assert.ok(!(await guest.call('catalog')).data.products.some(p=>p.id===product.id))});
await test('Newsletter consent and signature protections',async()=>{assert.equal((await guest.call('newsletter',{email:'qa-news-'+suffix+'@example.test',consent:false})).status,400);assert.equal((await guest.call('newsletter',{email:'qa-news-'+suffix+'@example.test',consent:true})).status,200);assert.equal((await fetch(origin+'/api/stripe/webhook',{method:'POST',body:'{}'})).status,400)});
await test('Image upload rejects disguised and oversized files',async()=>{const f=new FormData();f.append('files',new Blob(['<svg onload=alert(1)></svg>'],{type:'image/jpeg'}),'fake.jpg');assert.equal((await owner.call('admin/upload',f)).status,400);const f2=new FormData();f2.append('files',new Blob([new Uint8Array(6*1024*1024)],{type:'image/png'}),'large.png');assert.ok([400,413].includes((await owner.call('admin/upload',f2)).status))});
await test('Upload a real image and retrieve stored bytes',async()=>{const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j3u0AAAAASUVORK5CYII=','base64');const form=new FormData();form.append('files',new Blob([bytes],{type:'image/png'}),'qa-pixel.png');const r=await owner.call('admin/upload',form);assert.equal(r.status,200,JSON.stringify(r.data));const image=await fetch(origin+r.data.images[0].url);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.equal((await image.arrayBuffer()).byteLength,bytes.length)});
await test('Password reset token expires, is single-use, and revokes old sessions',async()=>{const d1='.wrangler/state/v3/d1/miniflare-D1DatabaseObject';const file=readdirSync(d1).find(f=>f.endsWith('.sqlite')&&f!=='metadata.sqlite');const sql=new DatabaseSync(d1+'/'+file,{readOnly:true});const recovery=new Client();await recovery.init();assert.equal((await recovery.call('auth/forgot',{email:customerEmail})).status,200);const job=sql.prepare("SELECT body FROM email_outbox WHERE recipient=? AND subject='Reset your Dress to Impress password' ORDER BY rowid DESC LIMIT 1").get(customerEmail);assert.ok(job);const resetToken=job.body.match(/token=([a-f0-9]+)/)[1];const fresh='New-'+password;assert.equal((await recovery.call('auth/reset',{token:'a'.repeat(64),password:fresh})).status,400);assert.equal((await recovery.call('auth/reset',{token:resetToken,password:fresh})).status,200);assert.equal((await customer.call('account')).status,401);await recovery.init();assert.equal((await recovery.call('auth/reset',{token:resetToken,password:fresh})).status,400);assert.equal((await recovery.call('auth/login',{email:customerEmail,password:fresh})).status,200);sql.close()});
await test('Public routes, product metadata, sitemap and 404 respond correctly',async()=>{const paths=['/','/shop','/product/the-everyday-blazer','/cart','/checkout','/account','/about','/contact','/faq','/shipping','/returns','/privacy','/terms','/admin/login','/sitemap.xml','/robots.txt'];for(const path of paths){const r=await fetch(origin+path);assert.equal(r.status,200,path)}assert.equal((await fetch(origin+'/product/not-a-product')).status,404);const detail=await(await fetch(origin+'/product/the-everyday-blazer')).text();assert.ok(detail.includes('The Everyday Blazer'));assert.ok(detail.includes('og:title'))});
await test('Logout removes session and account access',async()=>{assert.equal((await owner.call('auth/logout',{})).status,200);assert.equal((await owner.call('account')).status,401)});
const safe=x=>"'"+String(x).replaceAll("'","''")+"'";
const cleanup=[];
for(const id of tracked.orders){cleanup.push('DELETE FROM order_items WHERE order_id='+safe(id)+';','DELETE FROM email_outbox WHERE dedupe_key='+safe('order:'+id)+';','DELETE FROM orders WHERE id='+safe(id)+';','DELETE FROM checkout_items WHERE attempt_id='+safe(id.slice(4))+';','DELETE FROM checkout_attempts WHERE id='+safe(id.slice(4))+';');}
for(const uid of tracked.users){cleanup.push('DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE user_id='+safe(uid)+');','DELETE FROM orders WHERE user_id='+safe(uid)+';','DELETE FROM checkout_items WHERE attempt_id IN (SELECT id FROM checkout_attempts WHERE user_id='+safe(uid)+');','DELETE FROM checkout_attempts WHERE user_id='+safe(uid)+';','DELETE FROM users WHERE id='+safe(uid)+';');}
for(const id of tracked.products)cleanup.push('DELETE FROM products WHERE id='+safe(id)+';');
for(const id of tracked.categories)cleanup.push('DELETE FROM categories WHERE id='+safe(id)+';');
cleanup.push("DELETE FROM newsletter_subscribers WHERE email="+safe('qa-news-'+suffix+'@example.test')+';',"DELETE FROM rate_limits WHERE key LIKE 'auth-%' OR key LIKE 'reset:%';");
writeFileSync('.sites-runtime/qa-cleanup.sql',cleanup.join('\n'));
writeFileSync('tests/results.json',JSON.stringify({at:new Date().toISOString(),results},null,2));
console.log(results.filter(r=>r.passed).length+'/'+results.length+' checks passed');
if(results.some(r=>!r.passed))process.exitCode=1;

