import assert from 'node:assert/strict';
import {previewGate} from '../lib/preview-gate.ts';

const request = headers => new Request('https://store.personal.workers.dev/admin', {headers});
assert.equal((await previewGate(request(), {})).status, 503);
const env = {PREVIEW_ACCESS_PASSWORD: 'a'.repeat(64)};
const page=await previewGate(request(),env);
assert.equal(page.status,200);
assert.equal(page.headers.has('www-authenticate'),false);
assert.match(await page.text(),/Preview password/);
assert.equal((await previewGate(request({Authorization: 'Basic ' + btoa('owner:wrong')}), env)).status, 200);
assert.equal(await previewGate(request({Authorization: 'Basic ' + btoa('owner:' + env.PREVIEW_ACCESS_PASSWORD)}), env), null);
assert.equal((await previewGate(new Request('https://localhost/admin'), {})).status, 503);
assert.equal(await previewGate(new Request('http://localhost:5173/'), {}), null);
assert.equal(await previewGate(request(), {SITE_VISIBILITY: 'public'}), null);
const post=(password,origin='https://store.personal.workers.dev')=>new Request('https://store.personal.workers.dev/__preview',{method:'POST',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password})});
assert.equal((await previewGate(post('wrong'),env)).status,403);
assert.equal((await previewGate(post(env.PREVIEW_ACCESS_PASSWORD,'https://evil.example'),env)).status,403);
const signedIn=await previewGate(post(env.PREVIEW_ACCESS_PASSWORD),env);
assert.equal(signedIn.status,303);
const cookie=signedIn.headers.get('set-cookie');
assert.match(cookie,/HttpOnly; Secure; SameSite=Lax/);
assert.equal(await previewGate(request({Cookie:cookie.split(';')[0]}),env),null);
assert.equal((await previewGate(request({Cookie:cookie.split(';')[0]}),{PREVIEW_ACCESS_PASSWORD:'b'.repeat(64)})).status,200);
assert.equal((await previewGate(request({Cookie:'__Host-dti_preview=0000000000.'+'a'.repeat(64)}),env)).status,200);
assert.equal((await previewGate(post('a'.repeat(3000)),env)).status,413);
assert.equal((await previewGate(new Request('https://store.personal.workers.dev/api/admin'),env)).status,401);
console.log('PASS Preview form, signed secure cookie, expiry, password rotation, origin checks, body limit, API denial and legacy Basic access.');
