import {collectCod} from './cod';
import {currencyFactor} from './types';
import 'server-only';
import {all,one,run,stmt,db,uid,getStore,config} from './db';
import {AppError} from './auth';
import {refundOrder} from './commerce';
import {productSchema,settingsSchema,homeSchema,safeUrl} from './validation';
import {z} from 'zod';
export async function adminData(){
 const [store,orders,customers,subscribers]=await Promise.all([getStore(true),all('SELECT id,name,email,total,currency,status,payment_status,payment_method,demo,created_at FROM orders ORDER BY created_at DESC LIMIT 500'),all("SELECT u.id,u.name,u.email,u.created_at,COUNT(o.id) total_orders,COALESCE(SUM(CASE WHEN o.demo=0 AND o.payment_status='paid' THEN o.total ELSE 0 END),0) total_spending FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC LIMIT 500"),all('SELECT id,email,created_at FROM newsletter_subscribers ORDER BY created_at DESC LIMIT 500')]);
 return {...store,orders,customers,subscribers,setup:{payments:!!config('STRIPE_SECRET_KEY')&&!!config('STRIPE_WEBHOOK_SECRET'),email:!!config('EMAIL_API_KEY')&&!!config('EMAIL_FROM')}};
}
export async function saveProduct(body:any){
 const p=productSchema.parse(body),id=p.id||uid();if(!await one('SELECT id FROM categories WHERE id=?',p.categoryId))throw new AppError('Select an existing category.');
 const writes=[stmt('INSERT INTO products (id,name,slug,description,price,sale_price,sku,category_id,materials,care,featured,is_new,best_seller,published,demo) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,description=excluded.description,price=excluded.price,sale_price=excluded.sale_price,sku=excluded.sku,category_id=excluded.category_id,materials=excluded.materials,care=excluded.care,featured=excluded.featured,is_new=excluded.is_new,best_seller=excluded.best_seller,published=excluded.published,demo=excluded.demo,updated_at=CURRENT_TIMESTAMP',id,p.name,p.slug,p.description,p.price,p.salePrice,p.sku,p.categoryId,p.materials,p.care,+p.featured,+p.isNew,+p.bestSeller,+p.published,+p.demo),stmt('DELETE FROM product_images WHERE product_id=?',id)];
 p.images.forEach((image,i)=>writes.push(stmt('INSERT INTO product_images (id,product_id,url,alt,position) VALUES (?,?,?,?,?)',uid(),id,image.url,image.alt,i)));
 const old=await all('SELECT v.id,v.size,v.color,i.stock,i.threshold FROM product_variants v JOIN inventory i ON i.variant_id=v.id WHERE v.product_id=?',id);
 for(const v of p.variants){if(v.id&&!old.some(o=>o.id===v.id))throw new AppError('Variant does not belong to this product.');const vid=v.id||old.find(o=>o.size===v.size&&o.color===v.color)?.id||uid();writes.push(stmt('INSERT INTO product_variants (id,product_id,size,color) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET size=excluded.size,color=excluded.color',vid,id,v.size,v.color),stmt('INSERT INTO inventory (variant_id,stock,threshold) VALUES (?,?,?) ON CONFLICT(variant_id) DO UPDATE SET threshold=excluded.threshold',vid,v.stock,v.threshold));if(v.id&&v.expectedStock!==undefined&&v.stock!==v.expectedStock)writes.push(stmt('UPDATE inventory SET stock=CASE WHEN stock=? THEN ? ELSE -1 END WHERE variant_id=?',v.expectedStock,v.stock,vid));}
 const retained=new Set(p.variants.map(v=>v.id||old.find(o=>o.size===v.size&&o.color===v.color)?.id));for(const v of old)if(!retained.has(v.id))writes.push(stmt('DELETE FROM product_variants WHERE id=?',v.id));
 await db().batch(writes);return{id};
}
export async function adminAction(action:string,b:any){
 if(action==='products/save')return saveProduct(b);
 if(action==='products/delete'){await run('DELETE FROM products WHERE id=?',String(b.id));return{ok:true}}
 if(action==='products/duplicate'){const p=(await getStore(true)).products.find(p=>p.id===b.id);if(!p)throw new AppError('Product not found.',404);return saveProduct({...p,id:undefined,name:p.name+' (copy)',slug:p.slug+'-copy-'+uid().slice(0,6),sku:p.sku+'-'+uid().slice(0,6),published:false,featured:!!p.featured,isNew:!!p.isNew,bestSeller:!!p.bestSeller,demo:!!p.demo,variants:p.variants.map(v=>({...v,id:undefined})),images:p.images})}
 if(action==='products/publish'){await run('UPDATE products SET published=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',b.published?1:0,String(b.id));return{ok:true}}
 if(action==='inventory'){const v=z.object({id:z.string(),expectedStock:z.number().int().min(0),stock:z.number().int().min(0).max(100000),threshold:z.number().int().min(0).max(10000)}).parse(b);await run('UPDATE inventory SET stock=CASE WHEN stock=? THEN ? ELSE -1 END,threshold=? WHERE variant_id=?',v.expectedStock,v.stock,v.threshold,v.id);return{ok:true}}
 if(action==='categories/save'){const c=z.object({id:z.string().optional(),name:z.string().min(2).max(80),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),description:z.string().max(1000),image:safeUrl,position:z.number().int().min(0)}).parse(b);const id=c.id||uid();await run('INSERT INTO categories (id,name,slug,description,image,position) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,description=excluded.description,image=excluded.image,position=excluded.position',id,c.name,c.slug,c.description,c.image,c.position);return{id}}
 if(action==='categories/delete'){if(await one('SELECT id FROM products WHERE category_id=? LIMIT 1',String(b.id)))throw new AppError('Move products to another category before deleting this one.');await run('DELETE FROM categories WHERE id=?',String(b.id));return{ok:true}}
 if(action==='homepage'){const content=homeSchema.parse(b);await run("UPDATE homepage_content SET data=?,updated_at=CURRENT_TIMESTAMP WHERE id='home'",JSON.stringify(content));return{ok:true}}
 if(action==='settings'){const settings=settingsSchema.parse(b);if(settings.liveSales&&((settings.paymentMethod!=='cod'&&(!config('STRIPE_SECRET_KEY')||!config('STRIPE_WEBHOOK_SECRET')))||!settings.shippingCountries||!settings.email||!settings.shippingPolicy||!settings.returnPolicy))throw new AppError('Configure contact details, delivery countries and policies before enabling sales; card payments also require Stripe keys.');const current=(await getStore()).settings;if(current.currency!==settings.currency&&await one("SELECT id FROM checkout_attempts WHERE status='reserved' LIMIT 1"))throw new AppError('Resolve open checkouts before changing the currency.');const factor=currencyFactor(settings.currency)/currencyFactor(current.currency);await db().batch([stmt("UPDATE products SET price=CAST(round(price*?) AS INTEGER),sale_price=CASE WHEN sale_price IS NULL THEN NULL ELSE CAST(round(sale_price*?) AS INTEGER) END WHERE EXISTS(SELECT 1 FROM site_settings WHERE id='store' AND json_extract(data,'$.currency')=?)",factor,factor,current.currency),stmt("UPDATE site_settings SET data=?,updated_at=CURRENT_TIMESTAMP WHERE id='store' AND json_extract(data,'$.currency')=?",JSON.stringify(settings),current.currency)]);return{ok:true}}
 if(action==='orders/collect')return collectCod(String(b.id));
 if(action==='orders/status'){const next=z.enum(['pending','paid','processing','shipped','delivered','cancelled','refunded']).parse(b.status);const order=await one('SELECT * FROM orders WHERE id=?',String(b.id));if(!order)throw new AppError('Order not found.',404);const transitions:Record<string,string[]>={pending:['cancelled'],paid:['processing','cancelled','refunded'],processing:['shipped','cancelled','refunded'],shipped:['delivered','refunded'],delivered:['refunded'],cancelled:['refunded'],refunded:[]};if(order.payment_method==='cod'){Object.assign(transitions,{pending:['processing','cancelled'],processing:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[],refunded:[],paid:[]});}if(!transitions[order.status]?.includes(next))throw new AppError('That status change is not valid.');
 if(next==='refunded'){await refundOrder(order.id);return{ok:true}}await run("UPDATE orders SET status=?,payment_status=CASE WHEN payment_method='cod' AND ?='cancelled' THEN 'cod_cancelled' ELSE payment_status END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=?",next,next,order.id,order.status);return{ok:true}}
 if(action==='demo/delete'){if(await one("SELECT id FROM checkout_attempts WHERE demo=1 AND status='reserved' LIMIT 1"))throw new AppError('Resolve open demo checkouts first.');await db().batch([stmt('DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE demo=1)'),stmt("DELETE FROM email_outbox WHERE dedupe_key IN (SELECT 'order:'||id FROM orders WHERE demo=1)"),stmt('DELETE FROM orders WHERE demo=1'),stmt('DELETE FROM checkout_items WHERE attempt_id IN (SELECT id FROM checkout_attempts WHERE demo=1)'),stmt('DELETE FROM checkout_attempts WHERE demo=1'),stmt('DELETE FROM products WHERE demo=1')]);return{ok:true}}
 throw new AppError('Action not found.',404);
}

