import {z} from 'zod';
export const safeUrl=z.string().max(2048).refine(s=>s===''||s.startsWith('/api/media/')||s==='/favicon.svg'||/^https:\/\/[^\s]+$/.test(s),'Use an HTTPS image URL or an uploaded image.');
export const safeLink=z.string().max(2048).refine(s=>s===''||(/^\/(?!\/)/.test(s)&&!s.includes('\\'))||/^https:\/\/[^\s]+$/.test(s),'Use a relative link or HTTPS URL.');
export const email=z.string().trim().email().max(254).transform(s=>s.toLowerCase());
export const password=z.string().min(12,'Use at least 12 characters.').max(128);
export const addressSchema=z.object({name:z.string().trim().min(2).max(120),email,phone:z.string().max(30).optional().default(''),line1:z.string().trim().min(3).max(200),line2:z.string().max(200).optional().default(''),city:z.string().trim().min(2).max(100),postalCode:z.string().trim().min(2).max(20),country:z.string().regex(/^[A-Z]{2}$/,'Select a country.')});
export const productSchema=z.object({id:z.string().optional(),name:z.string().trim().min(2).max(150),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(160),description:z.string().min(10).max(6000),price:z.number().int().positive().max(100000000),salePrice:z.number().int().positive().nullable(),sku:z.string().min(2).max(80),categoryId:z.string().min(1),materials:z.string().max(2000),care:z.string().max(2000),featured:z.boolean(),isNew:z.boolean(),bestSeller:z.boolean(),published:z.boolean(),demo:z.boolean(),images:z.array(z.object({url:safeUrl,alt:z.string().min(3).max(250)})).min(1).max(12),variants:z.array(z.object({id:z.string().optional(),expectedStock:z.number().int().min(0).optional(),size:z.string().min(1).max(30),color:z.string().min(1).max(40),stock:z.number().int().min(0).max(100000),threshold:z.number().int().min(0).max(10000)})).min(1).max(100)}).refine(p=>p.salePrice===null||p.salePrice<p.price,'Sale price must be below the regular price.').refine(p=>new Set(p.variants.map(v=>v.size+'|'+v.color)).size===p.variants.length,'Each size and color combination must be unique.');
export const settingsSchema=z.object({name:z.string().min(2).max(100),logo:safeUrl,favicon:safeUrl,currency:z.enum(['USD','EUR','GBP','TRY','CAD','AUD']),email:z.union([email,z.literal('')]),phone:z.string().max(40),instagram:safeUrl,tiktok:safeUrl,otherSocial:safeUrl,shippingFee:z.number().int().min(0).max(10000000),taxRate:z.number().min(0).max(100),shippingCountries:z.string().max(500).refine(s=>s===''||s.split(',').every(c=>/^[A-Z]{2}$/.test(c.trim())),'Use comma-separated two-letter country codes.'),shippingPolicy:z.string().max(15000),returnPolicy:z.string().max(15000),privacyPolicy:z.string().max(15000),terms:z.string().max(15000),liveSales:z.boolean(),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),font:z.enum(['Italiana','Georgia'])});
export const homeSchema=z.object({heroImage:safeUrl,heading:z.string().min(3).max(160),description:z.string().max(500),ctaText:z.string().min(2).max(80),ctaLink:safeLink,promoText:z.string().max(200),promoLink:safeLink,promoActive:z.boolean(),aboutHeading:z.string().max(160),aboutDescription:z.string().max(2000),aboutImage:safeUrl,instagramCaption:z.string().max(300),gallery:z.array(safeUrl).max(12)});

