import {sqliteTable,text,integer,uniqueIndex,index,check} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
const id=()=>text('id').primaryKey(); const stamp=()=>text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`);
export const users=sqliteTable('users',{id:id(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),role:text('role').notNull().default('customer'),createdAt:stamp()});
export const admins=sqliteTable('admins',{userId:text('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),createdAt:stamp()});
export const customers=sqliteTable('customers',{userId:text('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}),createdAt:stamp()});
export const sessions=sqliteTable('sessions',{id:id(),tokenHash:text('token_hash').notNull().unique(),userId:text('user_id').references(()=>users.id,{onDelete:'cascade'}),csrf:text('csrf').notNull(),expires:integer('expires').notNull(),createdAt:stamp()},t=>[index('sessions_user_idx').on(t.userId)]);
export const resetTokens=sqliteTable('reset_tokens',{hash:text('hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expires:integer('expires').notNull(),used:integer('used').notNull().default(0)});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const categories=sqliteTable('categories',{id:id(),name:text('name').notNull().unique(),slug:text('slug').notNull().unique(),description:text('description').notNull().default(''),image:text('image').notNull().default(''),position:integer('position').notNull().default(0),createdAt:stamp()});
export const products=sqliteTable('products',{id:id(),name:text('name').notNull(),slug:text('slug').notNull().unique(),description:text('description').notNull(),price:integer('price').notNull(),salePrice:integer('sale_price'),sku:text('sku').notNull().unique(),categoryId:text('category_id').references(()=>categories.id,{onDelete:'set null'}),materials:text('materials').notNull().default(''),care:text('care').notNull().default(''),featured:integer('featured').notNull().default(0),isNew:integer('is_new').notNull().default(0),bestSeller:integer('best_seller').notNull().default(0),published:integer('published').notNull().default(0),demo:integer('demo').notNull().default(0),createdAt:stamp(),updatedAt:text('updated_at').notNull().default('')},t=>[check('product_price_positive',sql`${t.price}>0 AND (${t.salePrice} IS NULL OR (${t.salePrice}>0 AND ${t.salePrice}<${t.price}))`),index('products_published_category_idx').on(t.published,t.categoryId)]);
export const productImages=sqliteTable('product_images',{id:id(),productId:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),url:text('url').notNull(),alt:text('alt').notNull(),position:integer('position').notNull().default(0)},t=>[index('product_images_product_idx').on(t.productId)]);
export const productVariants=sqliteTable('product_variants',{id:id(),productId:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),size:text('size').notNull(),color:text('color').notNull()},t=>[uniqueIndex('product_variant_options_idx').on(t.productId,t.size,t.color)]);
export const inventory=sqliteTable('inventory',{variantId:text('variant_id').primaryKey().references(()=>productVariants.id,{onDelete:'cascade'}),stock:integer('stock').notNull().default(0),threshold:integer('threshold').notNull().default(3)},t=>[check('stock_not_negative',sql`${t.stock}>=0 AND ${t.threshold}>=0`)]);
export const carts=sqliteTable('carts',{id:id(),sessionId:text('session_id').notNull().unique().references(()=>sessions.id,{onDelete:'cascade'}),createdAt:stamp()});
export const cartItems=sqliteTable('cart_items',{id:id(),cartId:text('cart_id').notNull().references(()=>carts.id,{onDelete:'cascade'}),variantId:text('variant_id').notNull().references(()=>productVariants.id,{onDelete:'cascade'}),quantity:integer('quantity').notNull()},t=>[uniqueIndex('cart_variant_idx').on(t.cartId,t.variantId),check('cart_qty',sql`${t.quantity}>0 AND ${t.quantity}<=20`)]);
export const checkoutAttempts=sqliteTable('checkout_attempts',{id:id(),requestKey:text('request_key').notNull(),sessionId:text('session_id').notNull(),userId:text('user_id').references(()=>users.id,{onDelete:'set null'}),status:text('status').notNull().default('reserved'),email:text('email').notNull(),name:text('name').notNull(),address:text('address').notNull(),subtotal:integer('subtotal').notNull(),shipping:integer('shipping').notNull(),tax:integer('tax').notNull(),total:integer('total').notNull(),currency:text('currency').notNull(),demo:integer('demo').notNull(),stripeId:text('stripe_id').unique(),stripeUrl:text('stripe_url'),stripeParams:text('stripe_params'),expires:integer('expires').notNull(),createdAt:stamp()},t=>[uniqueIndex('attempt_request_idx').on(t.sessionId,t.requestKey)]);
export const checkoutItems=sqliteTable('checkout_items',{id:id(),attemptId:text('attempt_id').notNull().references(()=>checkoutAttempts.id,{onDelete:'cascade'}),variantId:text('variant_id').notNull().references(()=>productVariants.id),quantity:integer('quantity').notNull(),price:integer('price').notNull(),snapshot:text('snapshot').notNull()},t=>[check('checkout_qty',sql`${t.quantity}>0 AND ${t.quantity}<=20`),index('checkout_items_attempt_idx').on(t.attemptId)]);
export const orders=sqliteTable('orders',{id:id(),attemptId:text('attempt_id').notNull().unique().references(()=>checkoutAttempts.id),userId:text('user_id').references(()=>users.id,{onDelete:'set null'}),sessionId:text('session_id').notNull(),email:text('email').notNull(),name:text('name').notNull(),address:text('address').notNull(),subtotal:integer('subtotal').notNull(),shipping:integer('shipping').notNull(),tax:integer('tax').notNull(),total:integer('total').notNull(),currency:text('currency').notNull(),status:text('status').notNull().default('paid'),paymentStatus:text('payment_status').notNull(),demo:integer('demo').notNull(),createdAt:stamp(),updatedAt:text('updated_at').notNull().default('')},t=>[index('orders_user_idx').on(t.userId),index('orders_status_created_idx').on(t.status,t.createdAt)]);
export const orderItems=sqliteTable('order_items',{id:id(),orderId:text('order_id').notNull().references(()=>orders.id,{onDelete:'cascade'}),quantity:integer('quantity').notNull(),price:integer('price').notNull(),snapshot:text('snapshot').notNull()},t=>[index('order_items_order_idx').on(t.orderId)]);
export const addresses=sqliteTable('addresses',{id:id(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),data:text('data').notNull(),createdAt:stamp()},t=>[index('addresses_user_idx').on(t.userId)]);
export const newsletterSubscribers=sqliteTable('newsletter_subscribers',{id:id(),email:text('email').notNull().unique(),createdAt:stamp()});
export const siteSettings=sqliteTable('site_settings',{id:text('id').primaryKey(),data:text('data').notNull(),updatedAt:text('updated_at').notNull().default('')});
export const homepageContent=sqliteTable('homepage_content',{id:text('id').primaryKey(),data:text('data').notNull(),updatedAt:text('updated_at').notNull().default('')});
export const stripeEvents=sqliteTable('stripe_events',{id:id(),createdAt:stamp()});
export const emailOutbox=sqliteTable('email_outbox',{id:id(),dedupeKey:text('dedupe_key').notNull().unique(),recipient:text('recipient').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),createdAt:stamp()});


