'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Skeleton} from '@/components/ui/skeleton';
import {useStore,report} from './provider';
import {Field,AddressFields,blankAddress} from './forms';
import {Empty} from './shared';
import {money} from '@/lib/types';
export function AuthView({admin=false,initialMode='login',resetToken=''}:{admin?:boolean;initialMode?:string;resetToken?:string}){const {api,ready,refreshSession}=useStore();const [mode,setMode]=useState(initialMode),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[name,setName]=useState(''),[setupToken,setSetupToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');return <main id="main" className="auth-page"><a className="wordmark" href="/">dress to impress</a><span className="eyebrow">{admin?'STORE MANAGEMENT':'YOUR OWN LITTLE CORNER'}</span><h1>{mode==='register'?'Make yourself at home.':mode==='forgot'?'Forgot your password?':mode==='reset'?'A fresh start.':mode==='setup'?'Set up your store.':'Welcome back.'}</h1><p>{admin?'Secure access for the store owner.':mode==='register'?'Save your details and keep track of your edit.':'Sign in to your account to pick up where you left off.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const d=await api('auth/'+mode,{email,password:pw,name,setupToken,token:resetToken});if(mode==='forgot'||mode==='reset'){setMessage(d.message);if(mode==='reset'){setMode('login');await refreshSession()}}else{await refreshSession();window.location.assign(admin?'/admin':'/account')}}catch(e){report(e)}finally{setBusy(false)}}}>{(mode==='register'||mode==='setup')&&<Field label="Full name" name="name" value={name} onChange={setName} autoComplete="name"/>}{mode!=='reset'&&<Field label="Email address" name="email" type="email" value={email} onChange={setEmail} autoComplete="email"/>}{mode!=='forgot'&&<><Field label="Password" name="password" type="password" value={pw} onChange={setPw} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode!=='login'&&<small>Use at least 12 characters.</small>}</>}{mode==='setup'&&<Field label="Owner setup token" name="setupToken" value={setupToken} onChange={setSetupToken} type="password"/>}{message&&<p className="notice" role="status">{message}</p>}<button className="button full-width" disabled={busy||!ready}>{busy?'One moment…':mode==='register'?'Create account':mode==='forgot'?'Send reset link':mode==='reset'?'Save new password':mode==='setup'?'Create administrator':'Sign in'}</button></form><div className="auth-links">{mode==='login'?<><button onClick={()=>setMode('forgot')}>Forgot password?</button>{admin?<button onClick={()=>setMode('setup')}>First time? Set up the owner account</button>:<button onClick={()=>setMode('register')}>New here? Create an account</button>}</>:<button onClick={()=>setMode('login')}>Back to sign in</button>}<a href="/shop">Continue shopping</a></div>{mode==='setup'&&<p className="notice">Use the secret ADMIN_SETUP_TOKEN from your store configuration. Account creation is available only before the first administrator is created.</p>}</main>}
export function AccountView(){const {api,user,ready}=useStore();const [data,setData]=useState<any>(null),[name,setName]=useState(''),[address,setAddress]=useState<any>({...blankAddress}),[busy,setBusy]=useState(false);const load=()=>api('account').then(d=>{setData(d);setName(d.user.name)}).catch(report);useEffect(()=>{if(user)void load()},[user,api]);if(!ready)return <main id="main" className="section"><Skeleton className="h-80 w-full"/></main>;if(!user)return <AuthView/>;return <main id="main" className="account-page section"><div className="section-heading"><div><span className="eyebrow">YOUR ACCOUNT</span><h1>Hello, {user.name.split(' ')[0]}.</h1></div><button className="text-link" onClick={async()=>{try{await api('auth/logout',{});window.location.assign('/account')}catch(e){report(e)}}}>Sign out</button></div><Tabs defaultValue="orders"><TabsList variant="line"><TabsTrigger value="orders">Your orders</TabsTrigger><TabsTrigger value="profile">Profile</TabsTrigger><TabsTrigger value="addresses">Saved addresses</TabsTrigger></TabsList><TabsContent value="orders">{data?.orders.length?<div className="account-orders">{data.orders.map((o:any)=><a className="account-order" key={o.id} href={'/order/'+o.id}><div><strong>{o.id}</strong><span>{new Date(o.created_at+'Z').toLocaleDateString()}{o.demo?' · Demo order':''}</span></div><span className="status-badge">{o.status}</span><strong>{money(o.total,o.currency)}</strong></a>)}</div>:<Empty title="Your story starts here." text="When you place an order, you’ll find it here."/>}</TabsContent><TabsContent value="profile"><form className="narrow-form" onSubmit={async e=>{e.preventDefault();try{await api('account/profile',{name});toast.success('Profile saved')}catch(e){report(e)}}}><Field label="Full name" name="name" value={name} onChange={setName}/><p>{user.email}</p><button className="button">Save profile</button></form></TabsContent><TabsContent value="addresses"><div className="address-cards">{data?.addresses.map((a:any)=><div className="address-card" key={a.id}><strong>{a.name}</strong><p>{a.line1}<br/>{a.city}, {a.postalCode}<br/>{a.country}</p><button className="text-link" onClick={()=>setAddress(a)}>Edit</button><button className="text-link" onClick={async()=>{try{await api('account/address/delete',{id:a.id});await load();toast.success('Address removed')}catch(e){report(e)}}}>Remove</button></div>)}</div><form className="address-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('account/address',address);await load();setAddress({...blankAddress});toast.success('Address saved')}catch(e){report(e)}finally{setBusy(false)}}}><h2>{address.id?'Edit address':'Add a shipping address'}</h2><AddressFields value={address} onChange={setAddress}/><button className="button" disabled={busy}>Save address</button>{address.id&&<button type="button" className="button outline" onClick={()=>setAddress({...blankAddress})}>Cancel edit</button>}</form></TabsContent></Tabs></main>}

