'use client';
import {ArrowUpRight,Camera} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {useStore} from './provider';
import {Newsletter} from './shared';
export function InformationView({page}:{page:string}){const {settings,home}=useStore();if(page==='about')return <main id="main"><section className="brand-story about-story"><div className="brand-image"><img src={home.aboutImage} alt="Demo fashion editorial"/></div><div className="brand-copy"><span className="eyebrow">OUR POINT OF VIEW</span><h1 className="whitespace-pre-line">{home.aboutHeading}</h1><p>{home.aboutDescription}</p><p className="demo-note">Brand story placeholder · The owner can replace this introduction.</p><a href="/shop" className="button">Discover the collection<ArrowUpRight size={17}/></a></div></section><Newsletter/></main>;
 if(page==='contact')return <main id="main" className="information-page"><span className="eyebrow">LET’S TALK</span><h1>A little help, a little hello.</h1><p>For product questions and brand updates, find Dress to Impress on Instagram.</p><a href={settings.instagram} className="button" target="_blank" rel="noreferrer"><Camera size={18}/> @dress_to_impress894</a>{settings.email&&<p>Email: <a href={'mailto:'+settings.email}>{settings.email}</a></p>}{settings.phone&&<p>Phone: <a href={'tel:'+settings.phone}>{settings.phone}</a></p>}{!settings.email&&!settings.phone&&<p className="notice">Customer service email and phone details have not been provided yet.</p>}</main>;
 if(page==='faq')return <main id="main" className="information-page"><span className="eyebrow">HERE TO HELP</span><h1>The little details.</h1><Accordion type="single" collapsible>{[{q:'Is this collection available to buy?',a:settings.liveSales?'Published non-demo items can be purchased through secure checkout.':'This is a preview store. Demo checkout creates a test order without charging you or sending a shipment.'},{q:'How do I find the right size?',a:'Choose a product to view the available sizes and its size guide. Actual garment measurements must be confirmed by the store owner.'},{q:'Where do you ship?',a:settings.shippingPolicy},{q:'Can I return an item?',a:settings.returnPolicy},{q:'Do I need an account?',a:'Guest checkout is available. An optional account lets you save shipping addresses and view your order history.'},{q:'How can I contact the brand?',a:'Visit @dress_to_impress894 on Instagram, or check the contact page for configured customer service details.'}].map((f,i)=><AccordionItem value={String(i)} key={i}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion></main>;
 const pages:Record<string,{title:string;content:string}>={shipping:{title:'Shipping, considered.',content:settings.shippingPolicy},returns:{title:'Returns & exchanges.',content:settings.returnPolicy},privacy:{title:'Privacy policy.',content:settings.privacyPolicy},terms:{title:'Terms & conditions.',content:settings.terms}};
 const p=pages[page];return <main id="main" className="information-page"><span className="eyebrow">THE DETAILS</span><h1>{p.title}</h1><p className="policy-content">{p.content}</p><a href="/contact" className="text-link">Need a hand? Get in touch<ArrowUpRight size={17}/></a></main>}

