'use client';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import {Search,ShoppingBag,UserRound,Menu,ArrowUpRight,Camera,ArrowRight,Plus} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetTrigger} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {useStore,report} from './provider';
import {imageSet} from '@/lib/images';
import {money,type Product} from '@/lib/types';
export function Choice({value,onChange,options,label}:{value:string;onChange:(value:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value||'all'} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Check({checked,onChange,children}:{checked:boolean;onChange:(value:boolean)=>void;children:React.ReactNode}){return <label className="check-label"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname(),{settings,home,cart,categories}=useStore();const [search,setSearch]=useState(false),[term,setTerm]=useState('');
 if(path.startsWith('/admin'))return <>{children}</>;
 return <>{home.promoActive&&<a className="announcement" href={home.promoLink||'/shop'}>{home.promoText}</a>}<header className="site-header"><div className="mobile-menu"><Sheet><SheetTrigger aria-label="Open menu"><Menu/></SheetTrigger><SheetContent side="left"><SheetHeader><SheetTitle>{settings.name}</SheetTitle><SheetDescription>Find your next everyday favourite.</SheetDescription></SheetHeader><nav className="mobile-links"><a href="/shop">Shop all</a><a href="/shop?edit=new">New arrivals</a>{categories.map(c=><a key={c.id} href={'/shop?category='+encodeURIComponent(c.name)}>{c.name}</a>)}<a href="/about">Our story</a><a href="/account">My account</a></nav></SheetContent></Sheet></div><a className="wordmark" href="/">{settings.logo?<img src={settings.logo} alt={settings.name}/>:settings.name.toLowerCase()}<span>YOUR EVERYDAY, ELEVATED.</span></a><nav aria-label="Main navigation"><a href="/shop" className={path==='/shop'?'active':''}>Shop all</a><a href="/shop?edit=new">New arrivals</a><a href="/shop?category=Dresses">Dresses</a><a href="/about">Our story</a></nav><div className="header-actions"><button aria-label="Search the collection" onClick={()=>setSearch(true)}><Search/></button><a href="/account" aria-label="My account"><UserRound/></a><a href="/cart" aria-label={'Shopping bag, '+cart.reduce((n,l)=>n+l.quantity,0)+' items'} className="bag-icon"><ShoppingBag/>{cart.length>0&&<span>{cart.reduce((n,l)=>n+l.quantity,0)}</span>}</a></div></header>{children}<Footer/><Dialog open={search} onOpenChange={setSearch}><DialogContent><DialogHeader><DialogTitle>Find your next favourite</DialogTitle><DialogDescription>Search the collection by product or style.</DialogDescription></DialogHeader><form action="/shop" className="search-form"><label className="sr-only" htmlFor="search-term">Search</label><input id="search-term" name="q" placeholder="Try a dress, blazer or blouse…" value={term} onChange={e=>setTerm(e.target.value)}/><button className="button" aria-label="Search"><Search size={18}/></button></form></DialogContent></Dialog></>;
}
export function ProductCard({product:p}:{product:Product}){const {settings}=useStore();const stock=p.variants.reduce((n,v)=>n+v.stock,0);return <article className="product-card"><a className="product-image" href={'/product/'+p.slug}><img src={p.images[0]?.url} srcSet={imageSet(p.images[0]?.url)} sizes="(max-width:650px) 45vw, (max-width:1000px) 30vw, 23vw" alt={p.images[0]?.alt||p.name} loading="lazy" width="600" height="800"/><div className="product-badges">{!stock?<span>Out of stock</span>:p.salePrice?<span className="sale-badge">The special edit</span>:p.isNew?<span>New arrival</span>:p.bestSeller?<span>Best seller{p.demo?' · demo':''}</span>:null}</div><span className="product-quick" aria-hidden="true"><Plus size={16}/> Discover this piece</span></a><div className="product-info"><div><a href={'/product/'+p.slug}>{p.name}</a><span className="product-category">{p.category}</span></div><div className="product-price">{money(p.salePrice??p.price,settings.currency)}{p.salePrice&&<del>{money(p.price,settings.currency)}</del>}</div></div><div className="product-meta"><div className="color-dots">{[...new Set(p.variants.map(v=>v.color))].map(c=><span key={c} title={c} style={{background:({Oat:'#bcae97',Black:'#292827',Ivory:'#e8e4d8',Sand:'#baa994',Burgundy:'#592d35',Cream:'#e9dfbf',Beige:'#c6b5a0'} as Record<string,string>)[c]||'#bbb'}}/>)}</div>{p.demo===1&&<small>DEMO PRODUCT & PRICE</small>}</div></article>}
export function ProductGrid({products}:{products:Product[]}){return <div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>}
export function Newsletter(){const {api,ready}=useStore();const [email,setEmail]=useState(''),[consent,setConsent]=useState(false),[done,setDone]=useState(false),[busy,setBusy]=useState(false);return <section className="newsletter"><div><span className="eyebrow">LET’S KEEP IN TOUCH</span><h2>Good things. In your inbox.</h2><p>New pieces, fresh inspiration, and the next edit.</p></div>{done?<p role="status">You’re on the list. See you in the next edit.</p>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('newsletter',{email,consent});setDone(true)}catch(e){report(e)}finally{setBusy(false)}}}><div className="newsletter-input"><label className="sr-only" htmlFor="newsletter-email">Your email address</label><input id="newsletter-email" type="email" placeholder="Your email address" required value={email} onChange={e=>setEmail(e.target.value)}/><button aria-label="Subscribe" disabled={busy||!ready}><ArrowRight size={21}/></button></div><Check checked={consent} onChange={setConsent}>I agree to receive updates and the <a href="/privacy">privacy policy</a>.</Check></form>}</section>}
export function Footer(){const {settings}=useStore();return <footer><div className="footer-grid"><div><a className="wordmark" href="/">{settings.name.toLowerCase()}</a><p>A little more style. A little more you.</p><a className="text-link" href={settings.instagram} target="_blank" rel="noreferrer"><Camera size={17}/> @dress_to_impress894</a></div><div><h3>Explore</h3><a href="/shop">Shop all</a><a href="/shop?edit=new">New arrivals</a><a href="/shop?edit=best">Best sellers</a><a href="/about">Our story</a></div><div><h3>Here to help</h3><a href="/contact">Contact</a><a href="/faq">FAQs</a><a href="/shipping">Shipping</a><a href="/returns">Returns & exchanges</a></div><div><h3>Your space</h3><a href="/account">My account</a><a href="/cart">Shopping bag</a><a href="/admin">Store management</a>{settings.tiktok&&<a href={settings.tiktok}>TikTok</a>}{settings.otherSocial&&<a href={settings.otherSocial}>More from the brand</a>}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {settings.name}</span>{!settings.liveSales&&<span>Preview store · Demo photography, products and prices</span>}<div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><span>{settings.currency}</span></div></div></footer>}
export function Empty({title,text,link='/shop',label='Explore the collection'}:{title:string;text:string;link?:string;label?:string}){return <div className="empty-state"><ShoppingBag size={38}/><h2>{title}</h2><p>{text}</p><a className="button" href={link}>{label}<ArrowUpRight size={16}/></a></div>}

