'use client';
import {useState,useMemo} from 'react';
import {Search,SlidersHorizontal,X} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Slider} from '@/components/ui/slider';
import {Pagination,PaginationContent,PaginationItem,PaginationLink} from '@/components/ui/pagination';
import {useStore} from './provider';
import {Choice,Check,ProductGrid,Empty} from './shared';
import {money} from '@/lib/types';
export function ShopView({query}:{query:Record<string,string|undefined>}){
 const {products,categories,settings}=useStore();const [q,setQ]=useState(query.q||''),[category,setCategory]=useState(query.category||'all'),[size,setSize]=useState('all'),[color,setColor]=useState('all'),[available,setAvailable]=useState(false),[sort,setSort]=useState('featured'),[edit,setEdit]=useState(query.edit||'all'),[page,setPage]=useState(1);const ceiling=Math.max(20000,...products.map(p=>p.price));const [max,setMax]=useState(ceiling);
 const result=useMemo(()=>{let filtered=products.filter(p=>(!q||(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q.toLowerCase()))&&(category==='all'||p.category===category)&&(edit==='all'||edit==='new'&&p.isNew||edit==='best'&&p.bestSeller)&&(p.salePrice??p.price)<=max&&p.variants.some(v=>(size==='all'||v.size===size)&&(color==='all'||v.color===color)&&(!available||v.stock>0)));filtered=[...filtered].sort((a,b)=>sort==='low'?(a.salePrice??a.price)-(b.salePrice??b.price):sort==='high'?(b.salePrice??b.price)-(a.salePrice??a.price):sort==='newest'?b.createdAt.localeCompare(a.createdAt):b.featured-a.featured);return filtered},[products,q,category,edit,max,size,color,available,sort]);
 const reset=()=>{setQ('');setCategory('all');setSize('all');setColor('all');setAvailable(false);setEdit('all');setMax(ceiling);setPage(1)};
 const change=(fn:(v:any)=>void)=>(v:any)=>{fn(v);setPage(1)};
 const filters=<div className="filters"><div className="filter-head"><h3>Refine your edit</h3><button onClick={reset}>Clear all</button></div><label>Category</label><Choice label="Category" value={category} onChange={change(setCategory)} options={[{value:'all',label:'All categories'},...categories.map(c=>({value:c.name,label:c.name}))]}/><label>Size</label><div className="filter-sizes">{['all','XS','S','M','L','XL'].map(s=><button key={s} className={s===size?'selected':''} onClick={()=>change(setSize)(s)}>{s==='all'?'All':s}</button>)}</div><label>Color</label><Choice label="Color" value={color} onChange={change(setColor)} options={[{value:'all',label:'All colors'},...[...new Set(products.flatMap(p=>p.variants.map(v=>v.color)))].map(c=>({value:c,label:c}))]}/><label>Price up to {money(max,settings.currency)}</label><Slider aria-label="Maximum price" min={0} max={ceiling} step={500} value={[max]} onValueChange={v=>change(setMax)(v[0])}/><Check checked={available} onChange={change(setAvailable)}>In stock only</Check></div>;
 const pages=Math.ceil(result.length/8),actualPage=Math.min(page,Math.max(pages,1));
 return <main id="main" className="shop-page"><div className="page-intro"><span className="eyebrow">THE DRESS TO IMPRESS COLLECTION</span><h1>{edit==='new'?'The new arrivals.':edit==='best'?'The favourites edit.':category!=='all'?category+'.':'Your next favourite.'}</h1><p>Pieces to live in. Looks to make your own.</p></div><div className="catalog-toolbar"><div className="catalog-tabs">{[{value:'all',label:'All pieces'},{value:'new',label:'New arrivals'},{value:'best',label:'Best sellers'}].map(e=><button key={e.value} className={edit===e.value?'selected':''} onClick={()=>change(setEdit)(e.value)}>{e.label}</button>)}</div><span className="muted">{result.length} pieces</span></div><div className="catalog-layout"><aside className="desktop-filters">{filters}</aside><div><div className="catalog-controls"><div className="catalog-search"><Search size={18}/><input aria-label="Search products" placeholder="Search the collection" value={q} onChange={e=>change(setQ)(e.target.value)}/>{q&&<button aria-label="Clear search" onClick={()=>change(setQ)('')}><X size={16}/></button>}</div><div className="mobile-filter"><Sheet><SheetTrigger className="button outline"><SlidersHorizontal size={16}/>Filters</SheetTrigger><SheetContent side="left"><SheetHeader><SheetTitle>Refine your edit</SheetTitle><SheetDescription>Find the size, color and style for you.</SheetDescription></SheetHeader>{filters}</SheetContent></Sheet></div><Choice label="Sort products" value={sort} onChange={change(setSort)} options={[{value:'featured',label:'Featured'},{value:'newest',label:'Newest'},{value:'low',label:'Price: low to high'},{value:'high',label:'Price: high to low'}]}/></div>{result.length?<ProductGrid products={result.slice((actualPage-1)*8,actualPage*8)}/>:<div className="empty-state"><Search size={32}/><h2>No pieces found.</h2><p>Try a different search or clear a filter.</p><button className="button outline" onClick={reset}>Clear filters</button></div>}{pages>1&&<Pagination><PaginationContent>{Array.from({length:pages},(_,i)=><PaginationItem key={i}><PaginationLink href="#" isActive={actualPage===i+1} onClick={e=>{e.preventDefault();setPage(i+1);document.querySelector('.catalog-controls')?.scrollIntoView({behavior:'smooth'})}}>{i+1}</PaginationLink></PaginationItem>)}</PaginationContent></Pagination>}<p className="demo-note">Demo collection · All demo products, images, prices and popularity labels are illustrative.</p></div></div></main>
}

